### PR TITLE
Initial impl. of Rich header parser. Closes trailofbits/pe-parse#83

### PR DESCRIPTION
**Pull request by stefansiegfried**

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @stefansiegfried! I'll do a full review in a bit.

**Comment by woodruffw** [comment]
Proposed changes (sorry, GitHub won't let me use a diff to fill the review in):

```diff
diff --git a/pe-parser-library/include/parser-library/parse.h b/pe-parser-library/include/parser-library/parse.h
index 7bdae78..55f45b8 100644
--- a/pe-parser-library/include/parser-library/parse.h
+++ b/pe-parser-library/include/parser-library/parse.h
@@ -167,7 +167,7 @@ typedef struct _parsed_pe {
 // Resolve a Rich header product id / build number pair to a known
 // product name
 typedef std::pair<std::uint16_t, std::uint16_t> ProductKey;
-std::string GetRichProductName(std::uint16_t prodId, std::uint16_t buildNum);
+const std::string& GetRichProductName(std::uint16_t prodId, std::uint16_t buildNum);
 
 // get parser error status as integer
 std::uint32_t GetPEErr();
diff --git a/pe-parser-library/src/parse.cpp b/pe-parser-library/src/parse.cpp
index ac22f1e..54278c4 100644
--- a/pe-parser-library/src/parse.cpp
+++ b/pe-parser-library/src/parse.cpp
@@ -124,18 +124,20 @@ struct parsed_pe_internal {
 
 // The mapping of Rich header product id / build number pairs
 // to strings
-std::map<ProductKey, std::string> ProductMap = {
+static const std::map<ProductKey, const std::string> ProductMap = {
   {std::make_pair(1, 0), "Imported Functions"}
 };
 
+static const std::string kUnknownProduct = "<unknown>";
+
 // Resolve a Rich header product id / build number pair to a known
 // product name
-std::string GetRichProductName(std::uint16_t prodId, std::uint16_t buildNum) {
+const std::string& GetRichProductName(std::uint16_t prodId, std::uint16_t buildNum) {
   auto it = ProductMap.find(std::make_pair(prodId, buildNum));
   if (it != ProductMap.end()) {
     return it->second;
   } else {
-    return "<unknown>";
+    return kUnknownProduct;
   }
 }
 
```

**Comment by stefansiegfried** [comment]
> Cheers! This is really excellently documented and easy to read. I'll merge once CI goes through.

Thanks @woodruffw !  I'd like to continue iterating on this feature because there is a lot of useful information in the references you cited in #83.  For example, we can probably make the Rich header detection a bit more robust and we should also recalculate the Rich header checksum to detect modifications to it.

**Comment by woodruffw** [comment]
> For example, we can probably make the Rich header detection a bit more robust and we should also recalculate the Rich header checksum to detect modifications to it.

Yep, definitely! I'd be very happy to accept PRs for those features, as well as additions to the `ProductMap` where appropriate.

**Pull request merged**
