### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by jacwil**
* Explicit and consistent use of std namespace
* Prefer std::vector over std::list
* Never use std::endl

### CODE REVIEW

**Comment by jacwil** [comment]
Explicit use of std namespace because use was inconsistent even within files declaring `use namespace std;`, namely a combination of the following:
* uint32_t
* ::uint32_t
* std::uint32_t

Preference of std::vector over std::list and avoidance of std::endl are stated best by Jason Turner: https://www.youtube.com/watch?v=uzF4u9KgUWI

**Comment by alessandrogario** [comment]
Hello @jacwil!

This is great! We had already started moving away from `using namespace std`, thanks for helping us out with this task!

**Comment by jacwil** [comment]
@alessandrogario, always feel free to request from me to split a PR into two or more PRs. I tendency to glob too many changes into a single PR. In this case, I can split out the change to `std::vector` and the chance in definition of [`iterVAStr`](https://github.com/trailofbits/pe-parse/pull/74/commits/d999bffd511584070844bd64c61a6ec68eec6f92#diff-23635f9b7d819e65b959f4ac01878fe6R182) into a separate PR.

**Comment by woodruffw** [comment]
I'm okay with this being one PR, since it's all in the scope of cleanup.

**Comment by woodruffw** [comment]
Thanks @jacwil!

**Pull request merged**
