### PR TITLE
Pass resource by const pointer instead of value

### PR DESCRIPTION
**Pull request by ekilmer**
Found/Suggested by LGTM:

This parameter of type resource is 128 bytes - consider passing a const
pointer/reference instead.

### CODE REVIEW

**Comment by ekilmer** [comment]
It's worth noting that LGTM found this one, only because `resource` is a large struct, but not the other `iter*` methods that also pass by value instead of by reference

**Comment by woodruffw** [comment]
> It's worth noting that LGTM found this one, only because `resource` is a large struct, but not the other `iter*` methods that also pass by value instead of by reference

Hmm, I think we should go ahead and change all of them, then, for API consistency.

Also, what do you think about using `const &` instead of `const *`? That'll also avoid the structure copy and (I think) is more idiomatic in  C++.

**Comment by ekilmer** [comment]
> Hmm, I think we should go ahead and change all of them, then, for API consistency.

I think that's a good idea.

> Also, what do you think about using const & instead of const *? That'll also avoid the structure copy and (I think) is more idiomatic in C++.

I think that's a good idea, too.

**Comment by ekilmer** [comment]
We should look whether this PR affects `winchecksec` in a big way or not

**Comment by woodruffw** [comment]
> We should look whether this PR affects `winchecksec` in a big way or not

Dependabot should sanity-check it for us, but I _think_ it'll be fine: `winchecksec` only uses the `GetDataDirectoryEntry` API at the moment, so callback changes shouldn't affect it.

**Comment by ekilmer** [comment]
> winchecksec only uses the GetDataDirectoryEntry API at the moment, so callback changes shouldn't affect it.

Yeah, I couldn't find anything obvious. It also compiled and ran for me 👍 

I think this is ready for another review then

**Pull request merged**
