### PR TITLE
Issue 43 via codecvt

### LINKED ISSUE #43: Documentation request: Comparing of resource names is not obvious
I tried to extract a specific resource, lets call it "ABCD" out of an exe, so I used the dumper as a reference:

```cpp
int printRsrc(void *N, resource r) {
  if (r.name_str.length())
    cout << "Name (string): " << r.name_str << endl;
  return 0;
}
```

Output: ``Name (string): ABCD`` (as expected)

Then I replaced the code with
```cpp
int printRsrc(void *N, resource r) {
  if (r.name_str == "ABCD")
    // print something
```
And wondered why it never enters the if-block, also the debugger only showed "A" and I wondered whats going because it's a normal std::string and std::cout was somehow able to print it properly.

After 30min of confusion I noticed that these are UTF-16 strings (obviously, that's Windows) and that "std::cout" silently swallows 0-bytes instead of echoing \0.

So for C++11 one way to do it is e.g.:

```cpp
if (r.name_str.length() == 8 && !memcmp(u"ABCD", r.name_str.c_str(), 8))
```

Could a note about this be added somewhere? I assume this also confuses other devs for a few minutes :)

### PR DESCRIPTION
**Pull request by jacwil**
Fixes #43 by converting resource data directory strings to UTF-8. This change will require a modern gcc compiler due to use of codecvt for Unicode conversion.

### CODE REVIEW

**Comment by jacwil** [comment]
@woodruffw this PR is failing because Travis is using old compilers.

I have a proposed change to .travis.yml here. I can either add that commit to this PR or create a new separate PR for it. https://github.com/jacwil/pe-parse/commit/fb2f4083926c6e167b617963f45a11d15759dd84

I used https://github.com/boostorg/hana/blob/master/.travis.yml as a reference.

Feel free to let me know how you'd like me to proceed. Of course, please also feel free to address this in a way that seems more suitable for this repository to include pushing any changes to this or other PRs of mine as you see fit. I don't take offense to that sort of thing.

**Comment by woodruffw** [comment]
> I have a proposed change to .travis.yml here. I can either add that commit to this PR or create a new separate PR for it. [jacwil@fb2f408](https://github.com/jacwil/pe-parse/commit/fb2f4083926c6e167b617963f45a11d15759dd84)

Putting it in this PR is fine by me (as the first commit on the branch ideally, such that master will always be in a buildable state when merged).

**Comment by jacwil** [comment]
This plan is to abandon this PR and start a fresh branch once I get Travis configured to find codecvt. Both gcc and clang builds for Linux are failing at the moment.

Will resume the quest for codecvt at another time.

**Comment by jacwil** [comment]
Abandoning in favor of #81

**Pull request closed without merging**
